biblys/biblys

bin/console
composer.json
src/Biblys/Service/Images/ImagesService.php
src/Command/ImportImagesCommand.php
tests/Biblys/Service/Images/ImagesServiceTest.php

Une entrée en base de données est maintenant créé lorsqu'une nouvelle image de couverture est uploadé. Mais pour les fichiers d'images déjà présent, il n'existe pas d'entrée en base, si bien qu'elles sont invisible pour le site.
Ajouter une commande CLI `composer run images:import` pour lire les fichiers sur le disque et créer l'entrée correspondante en base.

Ajout d'une commande CLI pour importer les images

---

CHANGELOG.md
config.example.yml
controllers/common/php/_list.php
controllers/common/php/adm_checkout.php
controllers/common/php/adm_stock.php
controllers/common/php/article_edit.php
controllers/common/php/cart.php
controllers/common/php/log_myebooks.php
inc/Article.class.php
inc/Cart.class.php
inc/Media.class.php
inc/functions.php
public/common/js/common.js
src/AppBundle/Resources/views/Article/_cover.html.twig
src/AppBundle/Resources/views/Legacy/user_ebooks.html.twig
src/Biblys/Legacy/CartHelpers.php
src/Biblys/Service/Config.php
src/Biblys/Service/Images/ImagesService.php
src/Biblys/Service/TemplateService.php
src/Command/ImportImagesCommand.php
tests/AppBundle/Controller/Legacy/CartTest.php
tests/ArticleTest.php
tests/Biblys/Legacy/CartHelpersTest.php
tests/Biblys/Service/ConfigTest.php
tests/Biblys/Service/Images/ImagesServiceTest.php
tests/PostTest.php

Aujourd'hui, pour savoir si un article a une image de couverture associé, la classe `Media` doit vérifier la présence d'un fichier sur le disque.
Remplacer tous les usages de `Media` par le service ImagesService qui peut vérifier en base de données si l'article a une couverture associée.

Afficher toutes les images de couverture à l'aide du service ImagesService

---

CHANGELOG.md
src/AppBundle/Controller/MaintenanceController.php
src/AppBundle/Resources/views/Maintenance/disk-usage.html.twig
src/AppBundle/routes.yml
src/Biblys/Admin/Entry.php
src/Biblys/Test/ModelFactory.php
src/Command/ImportImagesCommand.php
tests/AppBundle/Controller/MaintenanceControllerTest.php

Il n'est pas possible aujourd'hui de voir dans l'espace d'admnistration l'espace disque occupé par les images.
Calculer l'espace disque occupé par les images enregistrées dans la table images et afficher le total dans une nouvelle page de l'administration.

Ajouter une page "Espace disque"

---

CHANGELOG.md
inc/constants.php
public/common/css/common.css
src/AppBundle/Controller/UserController.php
src/AppBundle/Resources/views/User/library.html.twig

Les livres dans la bibliothèque numérique étant classés par date d'ajout à la bibliothèque, il peut être difficile de retrouver un livre précis.
Ajouter un champ de recherche permettant de filtrer les livres affichés.

Permettre à un utilisateur de rechercher dans sa bibliothèque numérique

---

config.example.yml
src/Biblys/Service/Images/CdnService.php
src/Biblys/Service/Images/ImagesService.php
src/Biblys/Service/Images/WeservCdnService.php
src/Biblys/Service/TemplateService.php
tests/Biblys/Service/Images/ImagesServiceTest.php
tests/Biblys/Service/Images/WeservCdnServiceTest.php

Le nouveau service `ImagesService` ne permet pas d'utiliser un CDN pour afficher les images.
- Ajouter une option de configuration `images.cdn.service` qui lorsqu'elle a pour valeur `"weserv"` permet d'afficher les images via le CDN WeServ. 
- Utiliser une interface pour la classe WeServCdnService afin de pouvoir ajouter facilement d'autres services de CDN à l'avenir

Permettre d'utiliser un CDN pour l'affichage des images

---

CHANGELOG.md
bin/console
composer.json
composer.lock
controllers/common/php/adm_stock.php
inc/constants.php
src/AppBundle/Controller/MaintenanceController.php
src/AppBundle/Resources/views/Maintenance/disk-usage.html.twig
src/Biblys/Service/CurrentSite.php
src/Biblys/Service/InvalidSiteIdException.php
src/Command/OptimizeImagesCommand.php
tests/AppBundle/Controller/MaintenanceControllerTest.php

Certains sites Biblys occupent un espace disque très important à cause à la résolution inutilement élevée.
Ajouter un script d'optimisation des images en limitant la taille du plus grand côté à 2000 pixels.

Ajouter un script d'optimisation des images

---

CHANGELOG.md
bin/console
controllers/common/php/adm_stock.php
controllers/common/php/order_payment.php
inc/constants.php
src/AppBundle/Controller/MaintenanceController.php
src/AppBundle/Resources/views/Maintenance/disk-usage.html.twig
tests/AppBundle/Controller/MaintenanceControllerTest.php

Corrections
- Si un filtre éditeur est configuré, seuls les articles des éditeurs
concernés seront comptabilisés sur la page Espace disque.
- Lors du paiement par chèque l'adresse d'expédition du chèque n'était plus
affichée correctement. C'est corrigé.
- La photo sur la page de modification d'un exemplaire s'affichait en basse
résolution lorsqu'elle était cliquée. Ce n'est plus le cas.
- Le script de réinitialisation de la base de données renvoyait une erreur.
Maintenant, ça fonctionne.

Hotfix 2.84.1

---

CHANGELOG.md
generated-migrations/PropelMigration_1726037791.php

Afin de ne pas reposer sur une opération manuelle pour remplir les pays (table `countries`) et éviter de mettre l'intégralité des pays dans un fichier de code, on ajoute une migration qui s'occupe d'insérer les données dans la table `countries`.

Remplir la table `countries` par une migration.

---

CHANGELOG.md
bin/console
controllers/common/php/post_edit.php
inc/Event.class.php
inc/Media.class.php
inc/Post.class.php
src/AppBundle/Controller/MaintenanceController.php
src/AppBundle/Controller/PostController.php
src/AppBundle/Resources/views/Maintenance/disk-usage.html.twig
src/Biblys/Service/Images/ImagesService.php
src/Biblys/Service/TemplateService.php
src/Biblys/Test/ModelFactory.php
src/Command/ImportImagesCommand.php
src/Command/OptimizeImagesCommand.php
tests/AppBundle/Controller/MaintenanceControllerTest.php
tests/Biblys/Service/Images/ImagesServiceTest.php
tests/PostTest.php

Aujourd'hui, Biblys n'a pas de moyen de savoir s'il existe une illustration pour un billet de blog autrement qu'en interrogeant le système de fichiers.
Utiliser la table `images` pour les billets de blog [comme cela a été fait pour photos d'exemplaires](https://github.com/biblys/biblys/pull/42).

Gérer en base de données les illustrations de billets de blog

---

CHANGELOG.md
controllers/common/php/adm_media.php
inc/MediaFile.class.php
inc/constants.php
src/AppBundle/Resources/views/Gallery/_gallery.html.twig
src/Biblys/Test/EntityFactory.php
src/Biblys/Test/Helpers.php
src/Biblys/Test/ModelFactory.php
src/Command/ImportMediaCommand.php
tests/AppBundle/Resources/views/GalleryTemplatesTest.php
tests/MediaFileTest.php

- L'affichage d'une galerie pouvait déclencher une erreur. C'est corrigé.
- L'ajout d'un média pouvait échouer si le dossier parent contenait des
tirets ("-") dans son nom. Maintenant, ça marche.
- L'import de média pouvait échouer si le nom du fichier comportait une
extension inhabituelle. Ça n'arrivera plus.
- Les dossiers et fichiers sont désormais triés par ordre alphabétique sur
la page "Gestion des médias".

Correctif 2.86.3

---

CHANGELOG.md
controllers/common/php/people.php
inc/Media.class.php
inc/People.class.php
inc/constants.php
src/AppBundle/Controller/MaintenanceController.php
src/AppBundle/Controller/PeopleController.php
src/AppBundle/Resources/views/Maintenance/disk-usage.html.twig
src/AppBundle/Resources/views/People/show.html.twig
src/Biblys/Service/Images/ImageForModel.php
src/Biblys/Service/Images/ImagesService.php
src/Biblys/Service/TemplateService.php
src/Biblys/Test/ModelFactory.php
src/Command/ImportImagesCommand.php
src/Model/ImageQuery.php
tests/AppBundle/Controller/MaintenanceControllerTest.php
tests/Biblys/Service/Images/ImageForModelTest.php
tests/Biblys/Service/Images/ImagesServiceTest.php
tests/Model/ImageQueryTest.php
tests/PeopleTest.php

Aujourd'hui, Biblys n'a pas de moyen de savoir s'il existe un portrait pour un·e contributeur·ice autrement qu'en interrogeant le système de fichiers.
Utiliser la table `images` pour les  portraits de contributeur·ice [comme cela a été fait pour les illustrations de billet de blog](https://github.com/biblys/biblys/pull/98).

Gérer en base de données les portraits de contributeur·ice

---

CHANGELOG.md
inc/Event.class.php
inc/Media.class.php
src/AppBundle/Controller/MaintenanceController.php
src/AppBundle/Resources/views/Event/_event.html.twig
src/AppBundle/Resources/views/Maintenance/disk-usage.html.twig
src/Biblys/Service/Images/ImagesService.php
src/Biblys/Service/TemplateService.php
src/Biblys/Test/ModelFactory.php
src/Command/ImportImagesCommand.php
src/Model/ImageQuery.php
tests/AppBundle/Controller/MaintenanceControllerTest.php
tests/Biblys/Service/Images/ImagesServiceTest.php
tests/Model/ImageQueryTest.php

Aujourd'hui, Biblys n'a pas de moyen de savoir s'il existe une illustration pour un évènement autrement qu'en interrogeant le système de fichiers.
Utiliser la table `images` pour les illustrations d'évènements [comme cela a été fait pour les illustrations de billet de blog](https://github.com/biblys/biblys/pull/98).

Gérer en base de données les illustrations d'évènements

---

.gitignore
CHANGELOG.md
bin/console
composer.json
controllers/common/php/adm_article_files.php
generated-migrations/PropelMigration_1730188853.php
public/common/js/biblys-admin.js
schema.xml
src/AppBundle/Controller/FileController.php
src/Command/MigrateFilesCommand.php
src/Model/Base/Article.php
src/Model/Base/Download.php
src/Model/Base/DownloadQuery.php
src/Model/Base/File.php
src/Model/Base/FileQuery.php
src/Model/Base/Site.php
src/Model/Base/SiteQuery.php
src/Model/Base/User.php
src/Model/File.php
src/Model/Map/DownloadTableMap.php
src/Model/Map/FileTableMap.php
src/Model/Map/SiteTableMap.php
tests/Model/FileTest.php

Aujourd'hui, le stockage des fichiers téléchargeables est effectué dans un dossier commun pour tous les sites et les entrées en base correspondantes ne sont pas associées à un site.
- Associer les fichiers téléchargeables à un site en fonction du filtre éditeur
- Déplacer les fichiers dans le répertoire spécifique du site

Déplacer les fichiers téléchargeables dans le répertoire du site

---

CHANGELOG.md
controllers/common/php/adm_order.php
controllers/common/php/adm_stock.php
controllers/common/php/article_edit.php
controllers/common/php/cart.php
controllers/common/php/post_edit.php
controllers/common/php/publisher_edit.php
inc/constants.php
public/api.php
public/common/js/common.js
src/ApiBundle/Controller/ShippingController.php
src/Biblys/Service/Images/ImagesService.php
src/Biblys/Test/ModelFactory.php
src/Command/ImportImagesCommand.php
src/Model/ShippingFeeQuery.php
tests/ApiBundle/Controller/ShippingControllerTest.php
tests/Biblys/Service/Images/ImagesServiceTest.php
tests/Model/ShippingFeeQueryTest.php

- Le choix d'un mode d'expédition pouvait échouer sans erreur. C'est corrigé.
- Les champs d'ajout d'image n'autorisaient que certains formats. Ils autorisent désormais tous JPEG, PNG ou WebP.
- La contrainte du nombre d'articles dans une commande pour une tarifaire de frais de port n'était pas prise en compte. C'est maintenant le cas.

Correctif 3.0.2

---

CHANGELOG.md
assets/js/orders/order.js
controllers/common/php/order.php
inc/Order.class.php
inc/constants.php
src/AppBundle/Controller/OrderController.php
src/Model/Order.php
tests/Model/OrderTest.php

Lorsqu'une commande utilisant le mode d'expédition Mondial Relais est marquée comme expédiée, il n'est pas possible de préciser le numéro de suivi, et la ou la client·e ne reçoit pas de lien de suivi.
- Permettre à l'administrateur·ice de préciser le numéro de suivi lorsque la commande est marquée comme expédiée
- Inclure le lien de suivi dans le courriel de confirmation d'expédition
- Afficher un bouton de suivi de l'expédition sur la page de la commande

Gérer les numéros de suivi Mondial Relay

---

CHANGELOG.md
inc/Article.class.php
inc/constants.php
src/Biblys/Data/ArticleType.php
src/Biblys/Test/ModelFactory.php
src/Model/Article.php
tests/Model/ArticleTest.php

Aujourd'hui, il n'est pas possible d'afficher facilement, sur la page d'un article de type lot, les articles contenus dans le lot, ou les lots dans lequel l'article est contenu.
xtdo
Ajouter à l'entité `Article` les méthodes suivantes :
* `isBundle` : renvoie `true` pour un article de type **lot**, `false` sinon
* `getArticlesFromBundle` : renvoie une collection d'entité `Article` contenus dans le lot
* `isInABundle` : renvoie `true` si l'article fait partie d'un lot
* `getBundles` : renvoie les entités `Article` de type **lot** dont l'article fait partie
[Documenter les nouvelles méthodes](https://docs.biblys.fr/personnaliser/entites/article/#article-de-type-lot)

Permettre d'afficher le contenu d'un lot sur la page article

---

CHANGELOG.md
controllers/common/php/adm_stocks.php
controllers/common/php/post_edit.php
inc/Order.class.php
inc/Post.class.php
inc/constants.php
src/AppBundle/Controller/ArticleController.php
src/AppBundle/Controller/OrderController.php
src/AppBundle/Resources/views/Article/_list_pagination.html.twig
src/AppBundle/Resources/views/Article/articleAdminCatalog.html.twig
src/AppBundle/Resources/views/Event/_pagination.html.twig
src/AppBundle/Resources/views/Event/index.html.twig
src/AppBundle/Resources/views/Invitation/list.html.twig
src/AppBundle/Resources/views/Mailing/_pagination.html.twig
src/AppBundle/Resources/views/Mailing/contacts.html.twig
src/AppBundle/Resources/views/Main/_pagination.html.twig
src/AppBundle/Resources/views/Main/home-posts.html.twig
src/AppBundle/Resources/views/Order/index.html.twig
src/AppBundle/Resources/views/Payment/_pagination.html.twig
src/AppBundle/Resources/views/Payment/index.html.twig
src/AppBundle/Resources/views/Post/_pagination.html.twig
src/AppBundle/Resources/views/Post/index.html.twig
src/AppBundle/Resources/views/PostCategory/show.html.twig
src/AppBundle/Resources/views/Publisher/_pagination.html.twig
src/AppBundle/Resources/views/Publisher/index.html.twig
src/AppBundle/Resources/views/Utils/_pagination.html.twig
src/Biblys/Service/Pagination.php
tests/AppBundle/Controller/ArticleControllerTest.php
tests/AppBundle/Controller/OrderControllerTest.php
tests/Biblys/Service/PaginationTest.php

- Le bouton d'export des commandes pouvait apparaître même si le mode d'expédition Mondial Relay n'était pas activé. C'est corrigé.
- Il n'était pas possible de remplacer une illustration de billet de blog sans supprimer au préalable. C'est désormais possible.
- Les articles sans titres provoquaient l'affichage d'une ligne vide sur la page "Catalogue" de l'administration. Désormais, la mention "Article sans titre" est affichée.
- Les liens "billet précédent" et "billet suivant" pouvaient pointer vers des billets hors-ligne. Désormais, ils pointent uniquement vers des billets publiés.
- La création d'une demande de paiement Stripe pouvait échouer si le commande contenait un article gratuit. Maintenant, ça marche.

Correctif 3.1.2

---

CHANGELOG.md
inc/constants.php
src/AppBundle/Resources/views/Article/show.html.twig
src/AppBundle/Resources/views/User/library.html.twig

- Le lien pour aller à la page d'un article depuis la bibliothèque numérique n'était pas bon. C'est corrigé.

Correctif 3.1.3

---

CHANGELOG.md
src/AppBundle/Controller/AdminsController.php
src/AppBundle/Resources/layout/email-layout.html.twig
src/AppBundle/Resources/views/Admins/admin-welcome_email.html.twig
src/AppBundle/Resources/views/Admins/new.html.twig
src/Biblys/Service/CurrentUser.php
src/Biblys/Test/ModelFactory.php
src/Model/RightQuery.php
tests/AppBundle/Controller/AdminsControllerTest.php
tests/Model/RightQueryTest.php

Améliorer la gestions des admins

---

CHANGELOG.md
controllers/common/php/article_edit.php
inc/Article.class.php
inc/constants.php
public/common/js/article_edit.js
src/AppBundle/Controller/FeedController.php
src/Biblys/Noosfere/Noosfere.php
src/Biblys/Test/ModelFactory.php
tests/AppBundle/Controller/FeedControllerTest.php
tests/AppBundle/Controller/Legacy/ArticleEditTest.php
tests/ArticleTest.php
tests/Biblys/Noosfere/NoosfereTest.php

- Le flux RSS des actualités pouvait déclencher une erreur si un billet
d'actualité n'avait pas de contenu. Désormais, les billets sans contenu sont
ignorés lors de la génération du flux.
- La création d'un article attribué à un éditeur hors du filtre éditeur pouvait
provoquer une erreur. C'est corrigé.
- Lors de l'import d'un article depuis nooSFere, les prix en euros n'étaient pas
importés. Maintenant, ils le sont.

Correctif 3.3.2

---

CHANGELOG.md
controllers/common/php/list_xhr.php
inc/constants.php
src/ApiBundle/Controller/PaymentController.php
src/AppBundle/Resources/views/Article/_cartButton.html.twig
src/AppBundle/Resources/views/Payment/select-method.html.twig
src/Biblys/Service/PaymentService.php
src/Usecase/MarkOrderAsShippedUsecase.php
tests/AppBundle/Controller/PaymentControllerTest.php
tests/Usecase/MarkOrderAsShippedUsecaseTest.php

- Les commandes payées avec PayPal et PayPlug pouvaient ne pas être marquées
comme payées. C'est corrigé.
- Le marquage d'une commande numérique comme expédiée pouvait échouer sans 
erreur. Ça n'arrivera plus.

Correctif 3.5.1

---

CHANGELOG.md
inc/constants.php
src/Biblys/Service/QueryParamsService.php
tests/Biblys/Service/ParamsServiceTest.php
tests/Biblys/Service/QueryParamsServiceTest.php

- La présence d'un paramètre fbclid ajouté par Facebook dans l'URL de certaines 
pages pouvait provoquer une erreur. C'est corrigé.

Correctif 3.5.2

---

CHANGELOG.md
inc/constants.php
public/common/js/article_edit.js

- La création d'un contributeur, d'une collection, d'un éditeur ou d'un cycle depuis la page d'édition d'un article pouvait échouer. C'est corrigé.

Correctif 3.6.1

---

CHANGELOG.md
controllers/common/php/adm_ebooks.php
controllers/common/php/article_edit.php
inc/constants.php
public/common/js/article_edit.js
public/common/js/entity-search-field.js
src/AppBundle/Resources/views/StockItem/new.html.twig
src/AppBundle/Resources/views/Utils/_entity-search-field.html.twig

* La page des ventes numériques pouvaient mettre du temps à s'afficher si
le nombre de ventes était important. Elle affiche désormais pas défaut
uniquement les ventes du mois courant.
* La sélection d'un article depuis la page "Ajouter un exemplaire" ne 
déclenchait plus aucune action. Désormais, la sélection de l'article permettra
d'aller à la page d'ajout d'exemplaire pour cet article.
* Le pré-remplissage des champs Titre et EAN sur la page d'édition d'article
ne fonctionnait plus. C'est corrigé.
* La recherche automatique dans les bases externes n'était plus lancée lors de
la création d'un nouvel article avec des champs pré-remplis. C'est corrigé.

Correctif 3.7.1
